// F53 (second verification step) and D02 (passkeys) in real Chrome on a disposable server. F53: set-up, recovery codes, the two-step sign-in, a recovery code, removal, English,
// staff reset. D02 / F71: a CDP virtual authenticator (a real WebAuthn ceremony in the browser) creates an account without password or e-mail, signs in, adds and removes
// passkeys, proves itself for sensitive actions, deletes the account; the access code. axe on every state that appears. A ports 3200-3209.
// Usage: node tools/qa-a/auth-browser.mjs   (needs puppeteer-core and axe-core: npm i --no-save puppeteer-core axe-core)
import { spawn, spawnSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { mkdirSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = fileURLToPath(new URL('../..', import.meta.url));
const req = createRequire(root + 'package.json');
const puppeteer = (await import(pathToFileURL(req.resolve('puppeteer-core')).href)).default;
const axeSource = readFileSync(req.resolve('axe-core/axe.min.js'), 'utf8');
const { totpAt } = await import(pathToFileURL(join(root, 'factors.mjs')).href);
const dataDir = mkdtempSync(join(tmpdir(), 'terra-auth-'));
const shots = process.env.SHOTS_DIR || join(tmpdir(), 'terra-auth-shots');
mkdirSync(shots, { recursive: true });
const port = 3200 + Math.floor(Math.random() * 10); // A test ports 3200-3209
const base = `http://localhost:${port}`; // "localhost" is also what WebAuthn needs as a relying-party id
const env = { ...process.env, DATA_PATH: join(dataDir, 'a.sqlite'), PORT: String(port), HOST: '127.0.0.1', TERRA_NOVA_API_KEY: '', TRUST_PROXY: '1', TN_FORM_TOKENS: 'optional', TN_FORM_MIN_AGE_MS: '0', TN_FORM_LIMIT_SCALE: '1000' };
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
let failures = 0;
const check = (name, ok, detail = '') => { if (!ok) failures++; console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${ok ? '' : '  -> ' + String(detail).slice(0, 700)}`); };

const staffPw = (role) => /conserver : (\S+)/.exec(spawnSync(process.execPath, ['create-staff.mjs', `${role}@auth.test`, `${role} Auth`, role], { cwd: root, env, encoding: 'utf8' }).stdout)[1];
const agentPw = staffPw('agent');
const server = spawn(process.execPath, ['server.mjs'], { cwd: root, env, stdio: 'ignore' });
await wait(1500);
let ipCounter = 0;
const call = async (path, method = 'GET', body, cookie = '') => {
  const response = await fetch(base + path, { method, headers: { 'Content-Type': 'application/json', 'X-Forwarded-For': `10.93.0.${++ipCounter}`, ...(cookie ? { Cookie: cookie } : {}) }, body: body ? JSON.stringify(body) : undefined });
  return { status: response.status, data: await response.json().catch(() => ({})), cookie: (response.headers.getSetCookie().find((c) => c.startsWith('tn_session=')) || '').split(';')[0] };
};
const PW = 'password-long-1';
const browser = await puppeteer.launch({ executablePath: process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: 'new', args: ['--no-sandbox'] });
async function open(cookie, locale = 'fr') {
  const context = await browser.createBrowserContext();
  const page = await context.newPage();
  await page.setViewport({ width: 1280, height: 1100 });
  await page.setExtraHTTPHeaders({ 'X-Forwarded-For': `10.94.0.${++ipCounter}` });
  await page.evaluateOnNewDocument((lang) => { try { localStorage.setItem('lang', lang); } catch { /* blocked */ } }, locale);
  if (cookie) await page.setCookie({ name: 'tn_session', value: cookie.split('=')[1], url: base });
  const log = { dialogs: [], errors: [] };
  page.on('dialog', (d) => { log.dialogs.push(d.message()); d.dismiss().catch(() => {}); });
  page.on('pageerror', (e) => log.errors.push(e.message));
  await page.goto(base + '/', { waitUntil: 'networkidle0' });
  return { context, page, log };
}
const axe = async (page, label) => {
  await page.evaluate(axeSource);
  const violations = await page.evaluate(async () => (await axe.run(document, { runOnly: ['wcag2a', 'wcag2aa', 'wcag21a', 'wcag21aa', 'wcag22aa'] })).violations.map((v) => `${v.id}[${v.impact}] x${v.nodes.length}: ${v.nodes[0].target.join(' ')}`));
  check(`axe (${label}): no violations`, violations.length === 0, violations.join(' | '));
};
const type = async (page, selector, value) => { await page.focus(selector); await page.$eval(selector, (n) => { n.value = ''; }); await page.keyboard.type(value); };
const textOf = (page, selector) => page.$eval(selector, (n) => n.textContent.trim()).catch(() => null);
const clickButton = (page, scope, label) => page.evaluate((s, l) => { const b = [...document.querySelectorAll(`${s} button`)].find((x) => x.textContent.trim() === l); if (!b) return false; b.click(); return true; }, scope, label);

console.log('# F53. set-up in the portal');
await call('/api/auth/register', 'POST', { name: 'Zoé Auth', email: 'zoe@auth.test', password: PW });
let s = await open(null);
await type(s.page, '#login-form [name=email]', 'zoe@auth.test');
await type(s.page, '#login-form [name=password]', PW);
await s.page.click('#login-form button[type=submit]');
await s.page.waitForFunction(() => !document.querySelector('#member-area').hidden, { timeout: 10000 }).catch(() => {});
await s.page.evaluate(() => document.querySelector('#factors-panel').scrollIntoView());
await s.page.waitForFunction(() => /désactivée/.test(document.querySelector('#factors-state')?.textContent || ''), { timeout: 8000 }).catch(() => {});
const state0 = await textOf(s.page, '#factors-state');
check('the panel "Sécurité de mon compte" says, in words, that the step is off, and offers to turn it on', /Vérification en deux étapes : désactivée\./.test(state0) && await clickButton(s.page, '#factors-body', 'Activer la vérification en deux étapes'), state0);
await s.page.waitForSelector('#factors-body input[type=password]');
const focusedPw = await s.page.evaluate(() => document.activeElement?.type);
check('it asks for the password again first, with the focus already in the field', focusedPw === 'password', focusedPw);
await axe(s.page, 'set-up: password step');
await type(s.page, '#factors-body input[type=password]', 'wrong-password-123');
await clickButton(s.page, '#factors-body', 'Continuer');
await s.page.waitForFunction(() => /Erreur : Mot de passe incorrect/.test(document.querySelector('#factors-status')?.textContent || ''), { timeout: 6000 }).catch(() => {});
check('a wrong password is said where the person is looking, with the error cue, and they can retry', /^⚠ Erreur : Mot de passe incorrect\./.test(await textOf(s.page, '#factors-status')) && (await s.page.$eval('#factors-body input[type=password]', (n) => !n.disabled)), await textOf(s.page, '#factors-status'));
await type(s.page, '#factors-body input[type=password]', PW);
await s.page.keyboard.press('Enter');
await s.page.waitForSelector('#factors-body .factors-secret', { timeout: 8000 });
const setup = await s.page.evaluate(() => ({ secret: document.querySelector('.factors-secret').textContent.replace(/\s/g, ''), link: document.querySelector('#factors-body a').href, steps: document.querySelectorAll('#factors-body ol.factors-steps li').length, label: document.querySelector('.factors-secret').getAttribute('aria-label'), focus: document.activeElement?.name }));
check('the set-up shows three plain steps, the key to type, an "Ouvrir dans mon application" link (otpauth), and the focus is in the code field', /^[A-Z2-7]{32}$/.test(setup.secret) && setup.link.startsWith('otpauth://totp/') && setup.steps === 3 && /^Clé secrète : /.test(setup.label) && setup.focus === 'code', JSON.stringify(setup));
await (await s.page.$('#factors-panel')).screenshot({ path: join(shots, 'factors-setup.png') });
await axe(s.page, 'set-up: key and code step');
await type(s.page, '#factors-body input[name=code]', '000000');
await s.page.keyboard.press('Enter');
await s.page.waitForFunction(() => /Erreur : Ce code n’est pas bon/.test(document.querySelector('#factors-status')?.textContent || ''), { timeout: 6000 }).catch(() => {});
check('a wrong code is explained (check the phone\'s clock) and the same form stays open', /^⚠ Erreur : Ce code n’est pas bon\. Vérifiez l’heure/.test(await textOf(s.page, '#factors-status')) && Boolean(await s.page.$('#factors-body input[name=code]')));
await type(s.page, '#factors-body input[name=code]', totpAt(setup.secret, Date.now()));
await s.page.keyboard.press('Enter');
await s.page.waitForSelector('#factors-body .recovery-codes', { timeout: 8000 });
const codesView = await s.page.evaluate(() => ({ codes: [...document.querySelectorAll('.recovery-codes li')].map((li) => li.textContent), done: [...document.querySelectorAll('#factors-body button')].find((b) => b.textContent === 'Terminer')?.disabled, status: document.querySelector('#factors-status').textContent.trim() }));
check('activation shows the eight recovery codes once, with "Terminer" disabled until the person confirms they wrote them down', codesView.codes.length === 8 && codesView.codes.every((c) => /^[A-Z2-9]{5}-[A-Z2-9]{5}$/.test(c)) && codesView.done === true && /^✓ La vérification en deux étapes est activée\.$/.test(codesView.status), JSON.stringify(codesView));
await (await s.page.$('#factors-panel')).screenshot({ path: join(shots, 'factors-codes.png') });
await axe(s.page, 'recovery codes shown');
await s.page.click('#factors-body input[type=checkbox]');
await clickButton(s.page, '#factors-body', 'Terminer');
await s.page.waitForFunction(() => /Codes de secours restants : 8/.test(document.querySelector('#factors-state')?.textContent || ''), { timeout: 6000 }).catch(() => {});
const afterDone = await s.page.evaluate(() => ({ state: document.querySelector('#factors-state').textContent, text: document.querySelector('#factors-body').textContent }));
check('after "Terminer" the codes are gone from the page and the state says activated with 8 codes left', /Vérification en deux étapes : activée depuis le \d{2}\/\d{2}\/\d{4}\. Codes de secours restants : 8\./.test(afterDone.state) && !/[A-Z2-9]{5}-[A-Z2-9]{5}/.test(afterDone.text), JSON.stringify(afterDone));
await axe(s.page, 'second step active');
const activatedAt = Date.now();

console.log('\n# F53. signing in with the second step');
await s.page.evaluate(() => document.querySelector('#logout-button').click());
await s.page.waitForFunction(() => !document.querySelector('#guest-area').hidden, { timeout: 8000 });
await type(s.page, '#login-form [name=email]', 'zoe@auth.test');
await type(s.page, '#login-form [name=password]', PW);
await s.page.click('#login-form button[type=submit]');
await s.page.waitForFunction(() => !document.querySelector('#login-second').hidden, { timeout: 8000 }).catch(() => {});
const stepTwo = await s.page.evaluate(() => ({ firstHidden: document.querySelector('#login-first').hidden, memberHidden: document.querySelector('#member-area').hidden, focus: document.activeElement?.name, button: document.querySelector('#login-form button[type=submit]').textContent, status: document.querySelector('#login-status').textContent.trim(), emailDisabled: document.querySelector('#login-form [name=email]').disabled, pwValue: document.querySelector('#login-form [name=password]').value }));
check('a right password does not sign in: the form moves to the code step (focus in the code field, password cleared and kept out of the way), and says so', stepTwo.firstHidden && stepTwo.memberHidden && stepTwo.focus === 'code' && stepTwo.button === 'Vérifier le code' && /^✓ Mot de passe correct\. Il reste à saisir le code/.test(stepTwo.status) && stepTwo.emailDisabled && stepTwo.pwValue === '', JSON.stringify(stepTwo));
await axe(s.page, 'login: code step');
await (await s.page.$('#login-form')).screenshot({ path: join(shots, 'login-second-step.png') });
await type(s.page, '#login-form [name=code]', '111111');
await s.page.keyboard.press('Enter');
await s.page.waitForFunction(() => /Erreur :/.test(document.querySelector('#login-status')?.textContent || ''), { timeout: 6000 }).catch(() => {});
const wrong = await s.page.evaluate(() => ({ status: document.querySelector('#login-status').textContent.trim(), secondVisible: !document.querySelector('#login-second').hidden, member: !document.querySelector('#member-area').hidden }));
check('a wrong code is refused with the error cue and the tries left; the code step stays so the person can retry', /^⚠ Erreur : Code incorrect ou déjà utilisé\. Il vous reste \d+ tentatives?/.test(wrong.status) && wrong.secondVisible && !wrong.member, JSON.stringify(wrong));
await type(s.page, '#login-form [name=code]', totpAt(setup.secret, Math.max(Date.now(), activatedAt) + 30000));
await s.page.keyboard.press('Enter');
await s.page.waitForFunction(() => !document.querySelector('#member-area').hidden && document.activeElement?.id === 'member-name', { timeout: 10000 }).catch(() => {});
const signedIn = await s.page.evaluate(() => ({ member: !document.querySelector('#member-area').hidden, name: document.querySelector('#member-name').textContent, status: document.querySelector('#login-status').textContent.trim(), buttonBack: document.querySelector('#login-form button[type=submit]').textContent, firstVisible: !document.querySelector('#login-first').hidden, focus: document.activeElement?.id }));
check('the right code opens the space (focus on the member name); the login form is back to its first step for next time', signedIn.member && /Zoé Auth/.test(signedIn.name) && signedIn.firstVisible && signedIn.buttonBack === 'Se connecter' && signedIn.focus === 'member-name', JSON.stringify(signedIn));

console.log('\n# F53. a recovery code, then removal');
await s.page.evaluate(() => document.querySelector('#logout-button').click());
await s.page.waitForFunction(() => !document.querySelector('#guest-area').hidden, { timeout: 8000 });
await type(s.page, '#login-form [name=email]', 'zoe@auth.test');
await type(s.page, '#login-form [name=password]', PW);
await s.page.click('#login-form button[type=submit]');
await s.page.waitForFunction(() => !document.querySelector('#login-second').hidden, { timeout: 8000 });
await s.page.click('#login-recovery-toggle');
const toggled = await s.page.evaluate(() => ({ help: document.querySelector('#login-second-help').textContent, hiddenToggle: document.querySelector('#login-recovery-toggle').hidden, focus: document.activeElement?.name }));
await type(s.page, '#login-form [name=code]', codesView.codes[0].toLowerCase());
await s.page.keyboard.press('Enter');
await s.page.waitForFunction(() => !document.querySelector('#member-area').hidden, { timeout: 8000 }).catch(() => {});
check('"J\'ai perdu mon téléphone" explains what to type, and a recovery code (typed in lower case) opens the space', /codes de secours/.test(toggled.help) && toggled.hiddenToggle && toggled.focus === 'code' && await s.page.$eval('#member-area', (n) => !n.hidden), JSON.stringify(toggled));
await s.page.waitForFunction(() => /Un code de secours a servi à vous connecter\. Il vous en reste 7\./.test(document.querySelector('#notices-list')?.textContent || ''), { timeout: 12000 }).catch(() => {});
check('the news list tells the resident that a recovery code was used and how many remain', /Un code de secours a servi à vous connecter\. Il vous en reste 7\./.test(await textOf(s.page, '#notices-list')) && /Codes de secours restants : 7/.test(await textOf(s.page, '#factors-state')));
await s.page.evaluate(() => document.querySelector('#factors-panel').scrollIntoView());
await clickButton(s.page, '#factors-body', 'Désactiver la vérification en deux étapes');
await s.page.waitForSelector('#factors-body input[name=code]');
await axe(s.page, 'removal form');
await type(s.page, '#factors-body input[type=password]', PW);
await type(s.page, '#factors-body input[name=code]', codesView.codes[1]);
await s.page.keyboard.press('Enter');
await s.page.waitForFunction(() => /désactivée\./.test(document.querySelector('#factors-state')?.textContent || ''), { timeout: 8000 }).catch(() => {});
check('removal needs the password and a code; afterwards the state says "désactivée" and the confirmation is visible', /Vérification en deux étapes : désactivée\./.test(await textOf(s.page, '#factors-state')) && /^✓ La vérification en deux étapes est désactivée\.$/.test(await textOf(s.page, '#factors-status')), await textOf(s.page, '#factors-status') + ' | ' + await textOf(s.page, '#factors-state'));
await s.page.waitForFunction(() => /La vérification en deux étapes de votre compte a été désactivée\./.test(document.querySelector('#notices-list')?.textContent || ''), { timeout: 20000 }).catch(async () => { await s.page.evaluate('refreshAll()'); await wait(2000); });
check('and a news line records that the protection was turned off (so a stolen session cannot do it unseen)', /La vérification en deux étapes de votre compte a été désactivée\./.test(await textOf(s.page, '#notices-list')));
await s.page.click('#lang-toggle');
await s.page.waitForFunction(() => document.querySelector('#factors-title')?.textContent === 'My account security', { timeout: 8000 }).catch(() => {});
const english = await s.page.evaluate(() => ({ title: document.querySelector('#factors-title').textContent, state: document.querySelector('#factors-state').textContent, button: document.querySelector('#factors-body button')?.textContent, login: document.querySelector('#login-second-help').textContent }));
check('in English the panel, its state and its button read in English', english.title === 'My account security' && english.state === 'Two-step verification: off.' && english.button === 'Turn on two-step verification' && /Your password is correct/.test(english.login), JSON.stringify(english));
check('no browser dialog and no page error in the whole flow', s.log.dialogs.length === 0 && s.log.errors.length === 0, JSON.stringify([s.log.dialogs, s.log.errors]));
await s.context.close();

console.log('\n# F53. staff: reset for a resident who lost everything');
const lost = await call('/api/auth/register', 'POST', { name: 'Yan Perdu', email: 'yan@auth.test', password: PW });
const lostSetup = await call('/api/me/2fa/setup', 'POST', { password: PW }, lost.cookie);
await call('/api/me/2fa/enable', 'POST', { code: totpAt(lostSetup.data.secret, Date.now()) }, lost.cookie);
const agent = (await call('/api/auth/login', 'POST', { email: 'agent@auth.test', password: agentPw })).cookie;
s = await open(agent);
await s.page.waitForSelector('#citizens-panel');
await type(s.page, '#citizen-search', 'Yan');
await s.page.waitForFunction(() => document.querySelector('#citizens-list li[data-citizen]'), { timeout: 8000 });
const hasButton = await s.page.evaluate(() => [...document.querySelectorAll('#citizens-list li button')].some((b) => /Retirer la vérification en deux étapes de Yan Perdu/.test(b.textContent)));
const zoeRow = await (async () => { await type(s.page, '#citizen-search', 'Zoé'); await wait(900); return s.page.evaluate(() => [...document.querySelectorAll('#citizens-list li button')].some((b) => /Retirer la vérification/.test(b.textContent))); })();
check('the resident list offers the removal only for residents who have the step on', hasButton && !zoeRow, JSON.stringify([hasButton, zoeRow]));
await type(s.page, '#citizen-search', 'Yan');
await wait(900);
await s.page.evaluate(() => [...document.querySelectorAll('#citizens-list li button')].find((b) => /Retirer la vérification en deux étapes de Yan Perdu/.test(b.textContent)).click());
await s.page.waitForSelector('#citizens-list input[name=reason]');
await s.page.type('#citizens-list li[data-citizen] input[name=reason]', 'A perdu son téléphone et ses codes');
await s.page.evaluate(() => [...document.querySelectorAll('#citizens-list li button')].find((b) => /Confirmer le retrait pour Yan Perdu/.test(b.textContent)).click());
await s.page.waitForFunction(() => /Vérification en deux étapes retirée pour Yan Perdu/.test(document.querySelector('#citizens-status')?.textContent || ''), { timeout: 8000 }).catch(() => {});
check('staff must give a reason; afterwards the status says it is done and the resident can sign in with the password alone again', /Vérification en deux étapes retirée pour Yan Perdu\. Ses sessions sont fermées\./.test(await textOf(s.page, '#citizens-status')) && (await call('/api/auth/login', 'POST', { email: 'yan@auth.test', password: PW })).data.user?.email === 'yan@auth.test', await textOf(s.page, '#citizens-status'));
await s.context.close();

console.log('\n# F71. the counter: an agent opens an account, the resident changes the password');
s = await open(agent);
await s.page.waitForSelector('#counter-form');
await type(s.page, '#counter-form [name=name]', 'Noa Guichet');
await s.page.select('#counter-form [name=district]', 'Quartier sud');
await s.page.click('#counter-form button[type=submit]');
await s.page.waitForFunction(() => !document.querySelector('#citizens-secret').hidden, { timeout: 10000 }).catch(() => {});
const desk = await s.page.evaluate(() => ({ codes: [...document.querySelectorAll('#citizens-secret code')].map((c) => c.textContent), text: document.querySelector('#citizens-secret').textContent, focus: document.activeElement?.id, status: document.querySelector('#citizens-status').textContent.trim() }));
check('the agent opens an account from the form: the access code and the one-time password appear once, focused, with what to tell the resident', /^TN-/.test(desk.codes[0]) && desk.codes[1]?.length >= 16 && /Affichés une seule fois/.test(desk.text) && desk.focus === 'citizens-secret' && /^✓ Compte ouvert pour Noa Guichet\./.test(desk.status), JSON.stringify(desk));
await axe(s.page, 'counter account created');
await s.context.close();
const noa = await call('/api/auth/login', 'POST', { email: desk.codes[0], password: desk.codes[1] });
s = await open(noa.cookie);
await s.page.evaluate(() => document.querySelector('#password-title').scrollIntoView());
await s.page.waitForSelector('#password-body input[name=next]');
await type(s.page, '#password-body input[name=current]', desk.codes[1]);
await type(s.page, '#password-body input[name=next]', 'my-own-new-password-1');
await s.page.keyboard.press('Enter');
await s.page.waitForFunction(() => /Mot de passe changé/.test(document.querySelector('#factors-status')?.textContent || ''), { timeout: 8000 }).catch(() => {});
check('the resident chooses their own password in "Sécurité de mon compte": confirmed on the page, the one-time password stops working, the new one works', /^✓ Mot de passe changé\./.test(await textOf(s.page, '#factors-status')) && (await call('/api/auth/login', 'POST', { email: desk.codes[0], password: desk.codes[1] })).status === 401 && (await call('/api/auth/login', 'POST', { email: desk.codes[0], password: 'my-own-new-password-1' })).status === 200, await textOf(s.page, '#factors-status'));
await axe(s.page, 'password section');
await s.context.close();

console.log('\n# D02. passkeys in real Chrome (a virtual authenticator answers the real WebAuthn ceremony)');
async function openWithAuthenticator(cookie, locale = 'fr') {
  const session = await open(cookie, locale);
  const client = await (session.page.createCDPSession ? session.page.createCDPSession() : session.page.target().createCDPSession());
  await client.send('WebAuthn.enable');
  const { authenticatorId } = await client.send('WebAuthn.addVirtualAuthenticator', { options: { protocol: 'ctap2', transport: 'internal', hasResidentKey: true, hasUserVerification: true, isUserVerified: true, automaticPresenceSimulation: true } });
  const credentials = async () => (await client.send('WebAuthn.getCredentials', { authenticatorId })).credentials;
  return { ...session, client, credentials, authenticatorId };
}
s = await openWithAuthenticator(null);
const alt = await s.page.evaluate(() => ({ login: !document.querySelector('#login-alt').hidden, signup: !document.querySelector('#passkey-signup-form').hidden, label: document.querySelector('#login-form label').textContent.trim() }));
check('the sign-in form offers a passkey button and the page offers account creation without a password; the identifier field says "e-mail ou code d’accès"', alt.login && alt.signup && /Adresse e-mail ou code d’accès/.test(alt.label), JSON.stringify(alt));
await axe(s.page, 'sign-in and sign-up with passkey offered');
await type(s.page, '#passkey-signup-form [name=name]', 'Sam Sans Mot de Passe');
await s.page.click('#passkey-signup-form button[type=submit]');
await s.page.waitForFunction(() => !document.querySelector('#access-code-notice').hidden, { timeout: 15000 }).catch(() => {});
const signedUp = await s.page.evaluate(() => ({ member: !document.querySelector('#member-area').hidden, name: document.querySelector('#member-name').textContent, code: document.querySelector('#access-code-value').textContent, focus: document.activeElement?.id, status: document.querySelector('#passkey-signup-status').textContent.trim() }));
const samCode = signedUp.code;
check('a real WebAuthn ceremony creates an account with only a name: signed in, the access code shown and focused, no password and no e-mail anywhere', signedUp.member && /Sam Sans Mot de Passe/.test(signedUp.name) && /^TN-[A-HJ-NP-Z2-9]{4}-[A-HJ-NP-Z2-9]{4}$/.test(samCode) && signedUp.focus === 'access-code-notice', JSON.stringify(signedUp));
check('the virtual device now holds exactly one resident credential for this site', (await s.credentials()).length === 1 && (await s.credentials())[0].isResidentCredential === true && (await s.credentials())[0].rpId === 'localhost');
await (await s.page.$('#access-code-notice')).screenshot({ path: join(shots, 'access-code.png') });
await axe(s.page, 'access code notice');
await s.page.click('#access-code-dismiss');
await s.page.evaluate(() => document.querySelector('#factors-panel').scrollIntoView());
await s.page.waitForFunction(() => document.querySelectorAll('#passkeys-body .passkey-item').length === 1, { timeout: 8000 }).catch(() => {});
const panel = await s.page.evaluate(() => ({ identity: document.querySelector('#identity-line').textContent, items: [...document.querySelectorAll('#passkeys-body .passkey-item')].map((li) => li.textContent), state: document.querySelector('#factors-state').textContent }));
check('"Sécurité de mon compte" keeps the access code, lists the passkey with its dates, and the notice is gone after "J’ai noté mon code"', panel.identity.includes(samCode) && panel.items.length === 1 && /ajoutée le \d{2}\/\d{2}\/\d{4}/.test(panel.items[0]) && await s.page.$eval('#access-code-notice', (n) => n.hidden), JSON.stringify(panel));
await (await s.page.$('#factors-panel')).screenshot({ path: join(shots, 'passkeys-panel.png') });
await axe(s.page, 'passkey list');
const lastRemoval = await (async () => { await s.page.evaluate(() => document.querySelector('#passkeys-body .passkey-item button').click()); await wait(1500); return textOf(s.page, '#passkeys-status'); })();
check('the only way into the account cannot be removed by accident: the page says so (409 message), nothing is removed', /Erreur : C’est votre seul moyen de connexion/.test(lastRemoval) && (await s.credentials()).length === 1, lastRemoval);
await s.page.evaluate(() => document.querySelector('#logout-button').click());
await s.page.waitForFunction(() => !document.querySelector('#guest-area').hidden, { timeout: 8000 });
await s.page.click('#passkey-login');
await s.page.waitForFunction(() => !document.querySelector('#member-area').hidden, { timeout: 15000 }).catch(() => {});
const passkeyIn = await s.page.evaluate(() => ({ member: !document.querySelector('#member-area').hidden, name: document.querySelector('#member-name').textContent, focus: document.activeElement?.id, status: document.querySelector('#login-status').textContent.trim() }));
check('"Se connecter avec une clé d’accès" signs in with nothing typed (focus on the member name)', passkeyIn.member && /Sam Sans Mot de Passe/.test(passkeyIn.name), JSON.stringify(passkeyIn));
await s.page.evaluate(() => document.querySelector('#factors-panel').scrollIntoView());
await s.page.waitForFunction(() => document.querySelector('#passkeys-body .passkey-item'), { timeout: 8000 });
await clickButton(s.page, '#passkeys-body', 'Ajouter une clé d’accès');
await wait(2500);
const sameDevice = await textOf(s.page, '#passkeys-status');
check('adding a second passkey on the SAME device is refused by the device (one credential per account and device); the page says so in plain words, with the proof step done first, and nothing is added', /^⚠ Erreur : Cet appareil a déjà une clé d’accès pour ce compte\./.test(sameDevice) && (await s.credentials()).length === 1 && (await s.page.$$eval('#passkeys-body .passkey-item', (n) => n.length)) === 1, sameDevice);
await clickButton(s.page, '#factors-body', 'Activer la vérification en deux étapes');
await s.page.waitForSelector('#factors-body .factors-secret', { timeout: 15000 }).catch(() => {});
check('the second step can be set up on a password-less account too: the passkey is the proof', Boolean(await s.page.$('#factors-body .factors-secret')), await textOf(s.page, '#factors-status'));
await clickButton(s.page, '#factors-body', 'Annuler');
await s.page.evaluate(() => document.querySelector('#delete-form').scrollIntoView());
const deleteForm = await s.page.evaluate(() => ({ field: document.querySelector('#delete-password-field').hidden, note: !document.querySelector('#delete-proof-note').hidden, required: document.querySelector('#delete-form [name=password]').required }));
check('the delete form does not ask a password-less account for a password (it says it will ask for the passkey)', deleteForm.field && deleteForm.note && !deleteForm.required, JSON.stringify(deleteForm));
await s.page.click('#delete-form button[type=submit]');
await s.page.waitForFunction(() => !document.querySelector('#guest-area').hidden, { timeout: 15000 }).catch(() => {});
check('confirming with the passkey deletes the account and signs out, with the confirmation', /Votre compte a été supprimé/.test(await textOf(s.page, '#account-status')) && !(await s.page.$eval('#guest-area', (n) => n.hidden)), await textOf(s.page, '#account-status'));
check('and the deleted account\'s access code no longer signs in anything', (await call('/api/auth/login', 'POST', { email: samCode, password: PW })).status === 401);
check('no browser dialog and no page error during the whole passkey flow', s.log.dialogs.length === 0 && s.log.errors.length === 0, JSON.stringify([s.log.dialogs, s.log.errors]));
await s.context.close();

console.log('\n# D02. a password account adds a passkey; F71: no e-mail, an access code');
const mia = await call('/api/auth/register', 'POST', { name: 'Mia Mot de Passe', email: 'mia@auth.test', password: PW });
s = await openWithAuthenticator(mia.cookie);
await s.page.evaluate(() => document.querySelector('#factors-panel').scrollIntoView());
await s.page.waitForFunction(() => document.querySelector('#passkeys-body button'), { timeout: 8000 });
await clickButton(s.page, '#passkeys-body', 'Ajouter une clé d’accès');
await s.page.waitForSelector('#passkeys-body input[type=password]');
await axe(s.page, 'add a passkey: password step');
await type(s.page, '#passkeys-body input[type=password]', 'wrong-password-123');
await s.page.keyboard.press('Enter');
await s.page.waitForFunction(() => /Erreur : Mot de passe incorrect/.test(document.querySelector('#factors-status')?.textContent || ''), { timeout: 6000 }).catch(() => {});
check('adding a passkey asks for the password; a wrong one is refused with the error cue and no device prompt', /Erreur : Mot de passe incorrect/.test(await textOf(s.page, '#factors-status')) && (await s.credentials()).length === 0, await textOf(s.page, '#factors-status'));
await type(s.page, '#passkeys-body input[type=password]', PW);
await s.page.keyboard.press('Enter');
await s.page.waitForFunction(() => document.querySelectorAll('#passkeys-body .passkey-item').length === 1, { timeout: 15000 }).catch(() => {});
check('with the right password the device is asked, the passkey is listed', (await s.credentials()).length === 1 && (await s.page.$$eval('#passkeys-body .passkey-item', (n) => n.length)) === 1, await textOf(s.page, '#passkeys-status'));
await s.page.waitForFunction(() => /Une clé d’accès a été ajoutée à votre compte/.test(document.querySelector('#notices-list')?.textContent || ''), { timeout: 20000 }).catch(async () => { await s.page.evaluate('refreshAll()'); await wait(2000); });
check('and a news line records it (so a stranger adding one is seen)', /Une clé d’accès a été ajoutée à votre compte/.test(await textOf(s.page, '#notices-list')));
// a second device (another virtual authenticator) adds its own passkey with the password, then the first one is removed with the password
await s.client.send('WebAuthn.addVirtualAuthenticator', { options: { protocol: 'ctap2', transport: 'usb', hasResidentKey: true, hasUserVerification: true, isUserVerified: true, automaticPresenceSimulation: true } });
await s.client.send('WebAuthn.removeVirtualAuthenticator', { authenticatorId: s.authenticatorId }); // the first device is no longer present: only the second can answer
await clickButton(s.page, '#passkeys-body', 'Ajouter une clé d’accès');
await s.page.waitForSelector('#passkeys-body input[type=password]');
await type(s.page, '#passkeys-body input[type=password]', PW);
await s.page.keyboard.press('Enter');
await s.page.waitForFunction(() => document.querySelectorAll('#passkeys-body .passkey-item').length === 2 || /Erreur/.test(document.querySelector('#passkeys-status')?.textContent || ''), { timeout: 15000 }).catch(() => {});
const twoKeys = await s.page.evaluate(() => ({ items: document.querySelectorAll('#passkeys-body .passkey-item').length, status: document.querySelector('#passkeys-status').textContent.trim() }));
check('a second passkey (another device) can be added with the password: two entries and a confirmation', twoKeys.items === 2 && /^✓ Clé d’accès ajoutée/.test(twoKeys.status), JSON.stringify(twoKeys));
await s.page.evaluate(() => document.querySelector('#passkeys-body .passkey-item button').click());
await s.page.waitForSelector('#passkeys-body input[type=password]');
const removeHelp = await textOf(s.page, '#passkeys-body');
await type(s.page, '#passkeys-body input[type=password]', 'wrong-password-123');
await s.page.keyboard.press('Enter');
await s.page.waitForFunction(() => /Erreur : Mot de passe incorrect/.test(document.querySelector('#factors-status')?.textContent || '') && !document.querySelector('#passkeys-body form button[type=submit]').disabled, { timeout: 6000 }).catch(() => {});
const wrongRemoval = await textOf(s.page, '#factors-status');
await type(s.page, '#passkeys-body input[type=password]', PW);
await s.page.keyboard.press('Enter');
await s.page.waitForFunction(() => document.querySelectorAll('#passkeys-body .passkey-item').length === 1, { timeout: 8000 }).catch(() => {});
check('removing one asks for the password (a wrong one is refused), then removes it, and says so', /Pour retirer « .+ », saisissez votre mot de passe\./.test(removeHelp) && /\(2\)/.test(removeHelp) && /Mot de passe incorrect/.test(wrongRemoval) && (await s.page.$$eval('#passkeys-body .passkey-item', (n) => n.length)) === 1 && /^✓ Clé d’accès retirée\./.test(await textOf(s.page, '#passkeys-status')), JSON.stringify([removeHelp, wrongRemoval, await s.page.$eval('#passkeys-body .passkey-item', (n) => n.length), await textOf(s.page, '#passkeys-status'), await textOf(s.page, '#factors-status')]));
await s.page.evaluate(() => document.querySelector('#logout-button').click());
await s.page.waitForFunction(() => !document.querySelector('#guest-area').hidden, { timeout: 8000 });
await s.page.click('#passkey-login');
await s.page.waitForFunction(() => !document.querySelector('#member-area').hidden, { timeout: 15000 }).catch(() => {});
check('Mia signs in with the passkey without typing her address or password', /Mia Mot de Passe/.test(await textOf(s.page, '#member-name')), await textOf(s.page, '#login-status'));
await s.page.click('#lang-toggle');
await s.page.waitForFunction(() => document.querySelector('#passkeys-title')?.textContent === 'Passkeys', { timeout: 8000 }).catch(() => {});
const passkeysEnglish = await s.page.evaluate(() => ({ title: document.querySelector('#passkeys-title').textContent, add: [...document.querySelectorAll('#passkeys-body button')].map((b) => b.textContent), glossary: [...document.querySelectorAll('.glossary-list dt')].map((d) => d.textContent).filter((x) => /Passkey|Access code/.test(x)) }));
check('in English the passkey panel and the glossary entries read in English', passkeysEnglish.title === 'Passkeys' && passkeysEnglish.add.includes('Add a passkey') && passkeysEnglish.glossary.length === 2, JSON.stringify(passkeysEnglish));
await s.context.close();

// F71: registering without an e-mail address (password), then signing in with the code
s = await open(null);
await type(s.page, '#register-form [name=name]', 'Lou Sans Mail');
await type(s.page, '#register-form [name=password]', PW);
await s.page.click('#register-form button[type=submit]');
await s.page.waitForFunction(() => !document.querySelector('#access-code-notice').hidden, { timeout: 12000 }).catch(() => {});
const louCode = await textOf(s.page, '#access-code-value');
check('the e-mail field is optional: a name and a password create the account and show an access code, focused', /^TN-[A-HJ-NP-Z2-9]{4}-[A-HJ-NP-Z2-9]{4}$/.test(louCode) && await s.page.evaluate(() => document.activeElement?.id === 'access-code-notice'), louCode);
await s.page.evaluate(() => document.querySelector('#logout-button').click());
await s.page.waitForFunction(() => !document.querySelector('#guest-area').hidden, { timeout: 8000 });
await type(s.page, '#login-form [name=email]', louCode.toLowerCase());
await type(s.page, '#login-form [name=password]', PW);
await s.page.click('#login-form button[type=submit]');
await s.page.waitForFunction(() => !document.querySelector('#member-area').hidden, { timeout: 8000 }).catch(() => {});
check('the code, typed in lower case in the usual field with the password, signs in', /Lou Sans Mail/.test(await textOf(s.page, '#member-name')), await textOf(s.page, '#login-status'));
await s.context.close();

// a browser that has no WebAuthn: nothing about passkeys is offered and nothing breaks
const plain = await browser.createBrowserContext();
const plainPage = await plain.newPage();
await plainPage.evaluateOnNewDocument(() => { delete window.PublicKeyCredential; });
const plainErrors = [];
plainPage.on('pageerror', (e) => plainErrors.push(e.message));
await plainPage.goto(base + '/', { waitUntil: 'networkidle0' });
check('without WebAuthn support the passkey button and the passwordless sign-up are not shown, and the page still works', await plainPage.evaluate(() => document.querySelector('#login-alt').hidden && document.querySelector('#passkey-signup-form').hidden && !document.querySelector('#login-form').hidden) && plainErrors.length === 0, plainErrors.join(' | '));
await plain.close();

await browser.close();
server.kill();
await wait(400);
rmSync(dataDir, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 });
console.log(failures ? `\n${failures} FAILED` : '\nall auth UI checks passed');
process.exit(failures ? 1 : 0);
