// F83 (receipt with a reference) and F84 (agents answer directly) in real Chrome on a disposable server: the resident's confirmation, card, receipt page and
// the public check; the staff reply box with a draft that survives list refreshes, the answered / not answered filter, and what the resident then sees.
// F79 (themes: form, cards, filters for residents, reports and staff), F80 (priorities for agents: selector, badge, order, filter, dashboard). Later sections of this file cover the other triage features. A ports 3200-3209. Usage: node tools/qa-a/civic-browser.mjs
import { spawn, spawnSync } from 'node:child_process';
import { createRequire } from 'node:module';
import { mkdirSync, mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = fileURLToPath(new URL('../..', import.meta.url));
const req = createRequire(root + 'package.json');
const puppeteer = (await import(pathToFileURL(req.resolve('puppeteer-core')).href)).default;
const dataDir = mkdtempSync(join(tmpdir(), 'terra-civic-'));
const shots = process.env.SHOTS_DIR || join(tmpdir(), 'terra-civic-shots');
mkdirSync(shots, { recursive: true });
const port = 3200 + Math.floor(Math.random() * 10); // A test ports 3200-3209
const base = `http://127.0.0.1:${port}`;
const env = { ...process.env, DATA_PATH: join(dataDir, 'c.sqlite'), PORT: String(port), HOST: '127.0.0.1', TERRA_NOVA_API_KEY: '', TRUST_PROXY: '1', TN_FORM_TOKENS: 'optional', TN_FORM_MIN_AGE_MS: '0', TN_FORM_LIMIT_SCALE: '1000' };
const wait = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
let failures = 0;
const check = (name, ok, detail = '') => { if (!ok) failures++; console.log(`${ok ? 'PASS' : 'FAIL'}  ${name}${ok ? '' : '  -> ' + String(detail).slice(0, 600)}`); };

const staffPw = (role) => /conserver : (\S+)/.exec(spawnSync(process.execPath, ['create-staff.mjs', `${role}@civic.test`, `${role} Civic`, role], { cwd: root, env, encoding: 'utf8' }).stdout)[1];
const agentPw = staffPw('agent');
const server = spawn(process.execPath, ['server.mjs'], { cwd: root, env, stdio: 'ignore' });
await wait(1500);
let ipCounter = 0;
const call = async (path, method = 'GET', body, cookie = '') => {
  const response = await fetch(base + path, { method, headers: { 'Content-Type': 'application/json', 'X-Forwarded-For': `10.82.0.${++ipCounter}`, ...(cookie ? { Cookie: cookie } : {}) }, body: body ? JSON.stringify(body) : undefined });
  return { status: response.status, data: await response.json().catch(() => ({})), cookie: (response.headers.getSetCookie().find((c) => c.startsWith('tn_session=')) || '').split(';')[0] };
};
const zoe = (await call('/api/auth/register', 'POST', { name: 'Zoé Civic', email: 'zoe@civic.test', password: 'password-long-1' })).cookie;
const agent = (await call('/api/auth/login', 'POST', { email: 'agent@civic.test', password: agentPw })).cookie;

const browser = await puppeteer.launch({ executablePath: process.env.CHROME_PATH || 'C:/Program Files/Google/Chrome/Application/chrome.exe', headless: 'new', args: ['--no-sandbox'] });
async function open(cookie, locale = 'fr') {
  const context = await browser.createBrowserContext();
  const page = await context.newPage();
  await page.setViewport({ width: 1280, height: 1100 });
  await page.setExtraHTTPHeaders({ 'X-Forwarded-For': `10.83.0.${++ipCounter}` });
  await page.evaluateOnNewDocument((lang) => { try { localStorage.setItem('lang', lang); } catch { /* blocked */ } }, locale);
  if (cookie) await page.setCookie({ name: 'tn_session', value: cookie.split('=')[1], url: base });
  const log = { dialogs: [], errors: [] };
  page.on('dialog', (d) => { log.dialogs.push(d.message()); d.dismiss().catch(() => {}); });
  page.on('pageerror', (e) => log.errors.push(e.message));
  await page.goto(base + '/', { waitUntil: 'networkidle0' });
  return { context, page, log };
}
const fill = (page, selector, values) => page.evaluate((sel, vals) => { const f = document.querySelector(sel); for (const [name, value] of Object.entries(vals)) { f.elements[name].value = value; f.elements[name].dispatchEvent(new Event('input', { bubbles: true })); } }, selector, values);
const text = (page, selector) => page.$eval(selector, (n) => n.textContent.trim()).catch(() => null);
const cardOf = (page, area, subject) => page.evaluateHandle((sel, s) => [...document.querySelectorAll(`${sel} .message-card`)].find((c) => c.querySelector('h4')?.textContent === s) || null, area, subject);

console.log('# F83. the resident: confirmation, card, receipt, public check');
let s = await open(zoe);
await s.page.waitForSelector('#message-form [name=subject]');
await fill(s.page, '#message-form', { subject: 'Poubelle renversée devant l’école', body: 'La poubelle devant l’école du quartier est renversée depuis ce matin.' });
await s.page.click('#message-form button[type=submit]');
await s.page.waitForFunction(() => /Référence M-\d+/.test(document.querySelector('#message-status')?.textContent || ''), { timeout: 12000 }).catch(() => {});
const confirmation = await s.page.$eval('#message-status', (n) => ({ text: n.textContent.trim(), link: n.querySelector('a.receipt-link')?.getAttribute('href'), target: n.querySelector('a.receipt-link')?.target, rel: n.querySelector('a.receipt-link')?.rel, newTab: n.querySelector('a.receipt-link .visually-hidden')?.textContent }));
const id = /Référence M-(\d+)/.exec(confirmation.text)?.[1];
check('after sending, the confirmation gives the reference and a link to the receipt (new tab, announced as such)', Boolean(id) && confirmation.link === `/api/messages/${id}/receipt?lang=fr` && confirmation.target === '_blank' && confirmation.rel === 'noopener' && /nouvel onglet/.test(confirmation.newTab || ''), JSON.stringify(confirmation));
await s.page.waitForFunction(() => document.querySelector('#citizen-messages .message-card'), { timeout: 8000 });
const card = await s.page.evaluate(() => { const c = document.querySelector('#citizen-messages .message-card'); return { reference: c.querySelector('.message-reference')?.textContent, dates: c.querySelector('.message-dates')?.textContent, link: c.querySelector('a.receipt-link')?.getAttribute('href') }; });
check('the history card keeps the reference, the date in city time and the receipt link, so the proof can be found again later', card.reference === `Référence M-${id}` && /Reçu le \d{2}\/\d{2}\/\d{4} à \d{2}:\d{2} \(heure de la cité\)/.test(card.dates) && card.link === `/api/messages/${id}/receipt?lang=fr`, JSON.stringify(card));
await s.page.screenshot({ path: join(shots, 'resident-card.png') });
const receiptPage = await s.context.newPage();
await receiptPage.goto(`${base}${confirmation.link}`, { waitUntil: 'networkidle0' });
const receipt = await receiptPage.evaluate(() => ({ title: document.title, h1: document.querySelector('h1')?.textContent, text: document.body.textContent }));
const code = /([A-Z2-9]{5}-[A-Z2-9]{5})/.exec(receipt.text)?.[1];
check('the receipt page opens signed in: title with the reference, the verification code, the message and how to verify it', receipt.h1 === 'Accusé de réception' && receipt.title.includes(`M-${id}`) && Boolean(code) && receipt.text.includes('Poubelle renversée devant l’école') && /Vérifier un accusé de réception/.test(receipt.text), JSON.stringify([receipt.title, code]));
await receiptPage.screenshot({ path: join(shots, 'receipt-page.png') });
await receiptPage.close();
await s.page.evaluate(() => document.querySelector('#verifier').scrollIntoView());
await fill(s.page, '#verify-form', { reference: `m-${id}`, code: code.toLowerCase() });
await s.page.click('#verify-form button[type=submit]');
await s.page.waitForFunction(() => /Accusé valide/.test(document.querySelector('#verify-status')?.textContent || ''), { timeout: 8000 }).catch(() => {});
const valid = await s.page.$eval('#verify-status', (n) => ({ text: n.textContent.trim(), error: n.dataset.error }));
check('the public check confirms a valid receipt in words: reference, date in city time, type, state (no content)', /Accusé valide : la ville a bien reçu la demande M-\d+ le \d{2}\/\d{2}\/\d{4} à \d{2}:\d{2} \(heure de la cité\)\. Type : Question aux services\. État actuel : /.test(valid.text) && valid.error === 'false' && !/Poubelle/.test(valid.text), JSON.stringify(valid));
await fill(s.page, '#verify-form', { reference: `M-${id}`, code: 'AAAAA-AAAAA' });
await s.page.click('#verify-form button[type=submit]');
await s.page.waitForFunction(() => /ne correspondent à aucune demande/.test(document.querySelector('#verify-status')?.textContent || ''), { timeout: 8000 }).catch(() => {});
const invalid = await s.page.$eval('#verify-status', (n) => ({ text: n.textContent.trim(), error: n.dataset.error }));
check('a wrong code is said plainly with the error cue, and nothing else is revealed', /^⚠ Erreur : Cette référence et ce code ne correspondent à aucune demande reçue/.test(invalid.text) && invalid.error === 'true', JSON.stringify(invalid));
await s.page.click('#lang-toggle');
await s.page.waitForFunction(() => document.documentElement.lang === 'en', { timeout: 6000 }).catch(() => {});
await s.page.waitForFunction(() => /^Reference M-/.test(document.querySelector('#citizen-messages .message-reference')?.textContent || ''), { timeout: 8000 }).catch(() => {}); // the cards are rebuilt after the switch
const english = await s.page.evaluate(() => ({ heading: document.querySelector('#verifier-title').textContent, ref: document.querySelector('#citizen-messages .message-reference')?.textContent, link: document.querySelector('#citizen-messages a.receipt-link')?.textContent, dates: document.querySelector('#citizen-messages .message-dates')?.textContent }));
check('in English the check, the reference, the receipt link and the dates read in English', english.heading === 'Check a receipt' && english.ref === `Reference M-${id}` && /Acknowledgement of receipt \(to print or save\)/.test(english.link) && /Received on \d{2}\/\d{2}\/\d{4} at \d{2}:\d{2} \(city time\)/.test(english.dates), JSON.stringify(english));
await s.context.close();

console.log('\n# F84. staff answer directly');
s = await open(agent);
await s.page.waitForSelector('#staff-messages .message-card');
const staffCard = await cardOf(s.page, '#staff-messages', 'Poubelle renversée devant l’école');
const draftKey = `reply:${id}`;
const longText = 'Bonjour, nous avons transmis votre signalement au service de la voirie. Une équipe passe demain matin avant l’ouverture de l’école.';
await s.page.focus(`[data-draft="${draftKey}"]`);
await s.page.keyboard.type(longText.slice(0, 60));
await s.page.evaluate('refreshAll()'); // the list is rebuilt from the server, as every poll does
await wait(1200);
const kept = await s.page.evaluate((key) => { const f = document.querySelector(`[data-draft="${key}"]`); return { value: f?.value, focused: document.activeElement === f, caret: f?.selectionStart }; }, draftKey);
check('a half-written answer survives the list being rebuilt (text, focus and caret are still there)', kept.value === longText.slice(0, 60) && kept.focused && kept.caret === 60, JSON.stringify(kept));
await s.page.keyboard.type(longText.slice(60));
await s.page.evaluate((id2) => { [...document.querySelectorAll('#staff-messages .message-card')].find((c) => c.querySelector('h4')?.textContent === 'Poubelle renversée devant l’école').querySelectorAll('button').forEach((b) => { if (b.textContent === 'Envoyer la réponse') b.click(); }); }, id);
await s.page.waitForFunction(() => /Réponse envoyée à l’habitant/.test(document.querySelector('#staff-reply-status')?.textContent || ''), { timeout: 8000 }).catch(() => {});
const replyStatus = await s.page.$eval('#staff-reply-status', (n) => ({ text: n.textContent.trim(), error: n.dataset.error }));
await wait(500);
const after = await s.page.evaluate((subject, key) => { const c = [...document.querySelectorAll('#staff-messages .message-card')].find((x) => x.querySelector('h4')?.textContent === subject); return { reply: c.querySelector('.reply-text')?.textContent, head: c.querySelector('.reply-head')?.textContent, status: c.querySelector('.message-status')?.textContent, draft: document.querySelector(`[data-draft="${key}"]`)?.value, focused: document.activeElement?.dataset?.draft === key }; }, 'Poubelle renversée devant l’école', draftKey);
check('sending says so, names the request, says the state did not change; the thread shows the answer and who wrote it; the box is empty and has the focus', /Réponse envoyée à l’habitant \(demande M-\d+\)\. L’état de la demande n’a pas changé\./.test(replyStatus.text) && replyStatus.error === 'false' && after.reply === longText && /Réponse de agent Civic · \d{2}\/\d{2}\/\d{4}/.test(after.head) && /Reçue|À traiter|Reçu/i.test(after.status) && after.draft === '' && after.focused, JSON.stringify([replyStatus, after]));
await s.page.screenshot({ path: join(shots, 'staff-reply.png') });
await s.page.select('#staff-filter-reply', 'none');
await wait(300);
const unanswered = await s.page.evaluate(() => [...document.querySelectorAll('#staff-messages .message-card h4')].map((h) => h.textContent));
await s.page.select('#staff-filter-reply', 'some');
await wait(300);
const answered = await s.page.evaluate(() => [...document.querySelectorAll('#staff-messages .message-card h4')].map((h) => h.textContent));
check('the "Réponse" filter finds the requests without an answer and those with one (daily follow-up)', !unanswered.includes('Poubelle renversée devant l’école') && answered.includes('Poubelle renversée devant l’école'), JSON.stringify([unanswered, answered]));
const emptySend = await s.page.evaluate((subject) => { const c = [...document.querySelectorAll('#staff-messages .message-card')].find((x) => x.querySelector('h4')?.textContent === subject); [...c.querySelectorAll('button')].find((b) => b.textContent === 'Envoyer la réponse').click(); return true; }, 'Poubelle renversée devant l’école');
await wait(300);
check('an empty answer is refused where the person is looking, with the error cue (nothing sent)', emptySend && /^⚠ Erreur : Écrivez d’abord la réponse\./.test(await text(s.page, '#staff-reply-status')) && s.log.dialogs.length === 0);
await s.context.close();

console.log('\n# F84. what the resident then sees');
s = await open(zoe);
await s.page.waitForSelector('#citizen-messages .message-card');
const seen = await s.page.evaluate(() => { const c = document.querySelector('#citizen-messages .message-card'); return { reply: c.querySelector('.reply-text')?.textContent, head: c.querySelector('.reply-head')?.textContent, notice: document.querySelector('#notices-list')?.textContent }; });
check('the answer is on the resident\'s card, signed "Réponse de la ville" (no staff name), and the news list says the city answered', seen.reply === longText && /^Réponse de la ville · \d{2}\/\d{2}\/\d{4}/.test(seen.head) && !/agent Civic/.test(seen.head) && /La ville a répondu à votre demande « Poubelle renversée devant l’école »/.test(seen.notice) && seen.notice.includes(longText), JSON.stringify(seen));
await s.page.screenshot({ path: join(shots, 'resident-with-reply.png') });
await s.context.close();

console.log('\n# F79. themes: send with a theme, find requests and reports by theme');
// fixtures: two published reports by another resident, with different themes
const yan = (await call('/api/auth/register', 'POST', { name: 'Yan Civic', email: 'yan@civic.test', password: 'password-long-1' })).cookie;
const publish = async (subject, topic, title) => {
  const made = await call('/api/messages', 'POST', { subject, body: 'Un problème décrit avec assez de mots pour être accepté par le serveur.', kind: 'incident', location: 'Avenue du Centre, Centre-ville', topic }, yan);
  await call(`/api/messages/${made.data.id}/public`, 'POST', { consent: true, public_title: title, public_summary: 'Résumé public écrit pour que les autres habitants comprennent le problème.', district: 'Centre-ville' }, yan);
  return made.data.id;
};
await publish('Lampadaire éteint', 'voirie', 'Lampadaire éteint avenue du Centre');
await publish('Fuite d’eau', 'eau', 'Fuite d’eau devant le marché');
await publish('Bus en retard', 'transport', 'Bus T1 en retard chaque matin');
s = await open(zoe);
await s.page.waitForSelector('#message-topic option');
const options = await s.page.$$eval('#message-topic option', (o) => o.map((x) => [x.value, x.textContent]));
check('the request form has a "Thème" list from the server, "Autre sujet" preselected', options.length >= 9 && options.some(([v, label]) => v === 'eau' && label === 'Eau et énergie') && (await s.page.$eval('#message-topic', (n) => n.value)) === 'autre', JSON.stringify(options));
await s.page.select('#message-topic', 'eau');
await fill(s.page, '#message-form', { subject: 'Pression de l’eau trop faible', body: 'La pression de l’eau est très faible chez nous depuis hier soir, merci de vérifier.' });
await s.page.click('#message-form button[type=submit]');
await s.page.waitForFunction(() => document.querySelectorAll('#citizen-messages .message-card').length === 2, { timeout: 12000 }).catch(() => {});
const cardTopics = await s.page.$$eval('#citizen-messages .message-card', (cs) => cs.map((c) => [c.querySelector('h4').textContent, c.querySelector('.message-topic')?.textContent]));
check('each card says its theme in words (a request sent without one shows the default; an old one would say "Non précisé")', cardTopics.length === 2 && cardTopics.some(([h, tp]) => /Pression/.test(h) && tp === 'Thème : Eau et énergie') && cardTopics.some(([h, tp]) => /Poubelle/.test(h) && tp === 'Thème : Autre sujet'), JSON.stringify(cardTopics));
await s.page.select('#mine-filter-topic', 'eau');
await wait(300);
const onlyWater = await s.page.$$eval('#citizen-messages .message-card h4', (h) => h.map((x) => x.textContent));
await s.page.select('#mine-filter-topic', 'sante');
await wait(300);
const noneShown = await text(s.page, '#citizen-messages');
await s.page.select('#mine-filter-topic', '');
check('the resident filters their history by theme; an empty result says so', onlyWater.length === 1 && /Pression/.test(onlyWater[0]) && /Aucun message ne correspond à ces filtres/.test(noneShown), JSON.stringify([onlyWater, noneShown]));
await s.page.evaluate(() => document.querySelector('#public-panel').scrollIntoView());
await s.page.waitForFunction(() => document.querySelectorAll('#public-list li[data-public]').length === 3, { timeout: 12000 }).catch(() => {});
const reportsAll = await s.page.$$eval('#public-list li[data-public]', (ls) => ls.map((l) => l.querySelector('strong').textContent));
await s.page.select('#public-filter-topic', 'eau');
await wait(300);
const reportsWater = await s.page.$$eval('#public-list li[data-public]', (ls) => ls.map((l) => [l.querySelector('strong').textContent, l.textContent.includes('Thème : Eau et énergie')]));
await s.page.select('#public-filter-topic', 'logement');
await wait(300);
const reportsNone = await text(s.page, '#public-list');
check('published reports show their theme and can be filtered by it; an empty theme says so', reportsAll.length === 3 && reportsWater.length === 1 && reportsWater[0][1] && /Fuite/.test(reportsWater[0][0]) && /ne correspond à ce thème/.test(reportsNone), JSON.stringify([reportsAll, reportsWater, reportsNone]));
await s.page.select('#public-filter-topic', '');
await s.page.click('#public-list li[data-public] button');
await s.page.waitForFunction(() => /soutient cette demande/.test(document.querySelector('#public-list')?.textContent || ''), { timeout: 8000 }).catch(() => {});
const supportedFirst = await (async () => {
  const before = await s.page.$$eval('#public-list li[data-public] strong', (x) => x.map((n) => n.textContent));
  await s.page.select('#public-sort', 'supported');
  await wait(300);
  const after = await s.page.$$eval('#public-list li[data-public] strong', (x) => x.map((n) => n.textContent));
  const supported = await s.page.$eval('#public-list li[data-public]', (l) => /soutient cette demande/.test(l.textContent));
  return { before, after, supported };
})();
check('"Les plus soutenues d’abord" puts the supported report first', supportedFirst.supported && supportedFirst.after.length === 3, JSON.stringify(supportedFirst));
await s.page.click('#lang-toggle');
await s.page.waitForFunction(() => document.querySelector('#message-topic option[value=eau]')?.textContent === 'Water and energy', { timeout: 8000 }).catch(() => {});
await s.page.waitForFunction(() => /^Subject area: /.test(document.querySelector('#citizen-messages .message-topic')?.textContent || ''), { timeout: 8000 }).catch(() => {});
const englishTopics = await s.page.evaluate(() => ({ form: document.querySelector('#message-topic option[value=eau]')?.textContent, filter: document.querySelector('#mine-filter-topic option[value=""]')?.textContent, card: document.querySelector('#citizen-messages .message-topic')?.textContent, label: document.querySelector('label:has(#message-topic)')?.firstChild?.textContent.trim(), sort: document.querySelector('#public-sort option[value=supported]')?.textContent }));
check('in English the theme names, the filter wording, the card line and the sort read in English', englishTopics.form === 'Water and energy' && englishTopics.filter === 'All subject areas' && /^Subject area: /.test(englishTopics.card) && englishTopics.label === 'Subject area of the request' && englishTopics.sort === 'Most supported first', JSON.stringify(englishTopics));
await s.context.close();
s = await open(agent);
await s.page.waitForSelector('#staff-messages .message-card');
await s.page.select('#staff-filter-topic', 'eau');
await wait(300);
const staffWater = await s.page.$$eval('#staff-messages .message-card h4', (h) => h.map((x) => x.textContent));
await s.page.select('#staff-filter-topic', 'none');
await wait(300);
const staffNone = await text(s.page, '#staff-messages');
check('staff narrow the list by theme (the follow-up by theme), and the no-theme choice finds nothing when every request has one', staffWater.length === 2 && staffWater.some((h) => /Pression/.test(h)) && staffWater.some((h) => /Fuite/.test(h)) && /Aucun message ne correspond à ces filtres/.test(staffNone), JSON.stringify([staffWater, staffNone]));
await s.page.screenshot({ path: join(shots, 'staff-topic-filter.png') });

console.log('\n# F80. priorities in the staff workspace');
await s.page.select('#staff-filter-topic', '');
await wait(300);
const titles = () => s.page.$$eval('#staff-messages .message-card h4', (h) => h.map((x) => x.textContent));
const before = await titles();
check('without priorities, the unresolved requests come newest first', /Pression/.test(before[0]) && /Poubelle/.test(before[before.length - 1]) , JSON.stringify(before));
const picked = await s.page.evaluate(() => { const c = [...document.querySelectorAll('#staff-messages .message-card')].find((x) => /Lampadaire/.test(x.querySelector('h4').textContent)); const select = c.querySelector('[data-priority-for]'); select.focus(); return { id: select.dataset.priorityFor, options: [...select.options].map((o) => o.textContent), label: select.getAttribute('aria-label') }; });
check('each staff card has a labelled priority selector (Urgente / Prioritaire / Normale), at "Normale" by default', JSON.stringify(picked.options) === JSON.stringify(['Urgente', 'Prioritaire', 'Normale']) && /^Priorité de la demande \d+$/.test(picked.label), JSON.stringify(picked));
await s.page.select(`[data-priority-for="${picked.id}"]`, 'urgent');
await s.page.waitForFunction(() => /Priorité de la demande M-\d+ : urgente\./.test(document.querySelector('#staff-reply-status')?.textContent || ''), { timeout: 8000 }).catch(() => {});
await wait(500);
const afterUrgent = await s.page.evaluate((id) => ({ first: document.querySelector('#staff-messages .message-card h4')?.textContent, badge: document.querySelector('#staff-messages .message-card .message-priority')?.textContent, focused: document.activeElement?.dataset?.priorityFor === id, status: document.querySelector('#staff-reply-status')?.textContent.trim(), value: document.querySelector(`[data-priority-for="${id}"]`)?.value }), picked.id);
check('setting "Urgente" says so in words, moves the request to the top, shows a badge with a symbol and text, and keeps the focus on the selector', /Lampadaire/.test(afterUrgent.first) && afterUrgent.badge === '⚠ Urgente' && afterUrgent.focused && afterUrgent.value === 'urgent' && /Priorité de la demande M-\d+ : urgente\./.test(afterUrgent.status), JSON.stringify(afterUrgent));
await s.page.screenshot({ path: join(shots, 'staff-priority.png') });
await s.page.select('#staff-filter-priority', 'urgent');
await wait(300);
const urgentOnly = await titles();
await s.page.select('#staff-filter-priority', '');
await s.page.select('#staff-sort', 'oldest');
await wait(300);
const oldest = await titles();
await s.page.select('#staff-sort', 'recent');
await wait(300);
const recent = await titles();
await s.page.select('#staff-sort', '');
check('staff filter by priority, and sort by oldest or newest first when they prefer to follow the waiting time', urgentOnly.length === 1 && /Lampadaire/.test(urgentOnly[0]) && /Poubelle/.test(oldest[0]) && /Pression/.test(recent[0]), JSON.stringify([urgentOnly, oldest, recent]));
const tile = await s.page.evaluate(() => { const link = [...document.querySelectorAll('#dashboard-tiles a')].find((a) => /Demandes urgentes non résolues/.test(a.getAttribute('aria-label'))); const todo = document.querySelector('#dashboard-todo')?.textContent; return { count: link?.textContent, todo }; });
await s.page.evaluate('refreshAll()');
await wait(1500);
const tile2 = await s.page.evaluate(() => { const link = [...document.querySelectorAll('#dashboard-tiles a')].find((a) => /Demandes urgentes non résolues/.test(a.getAttribute('aria-label'))); return { count: link?.textContent, todo: document.querySelector('#dashboard-todo')?.textContent }; });
check('the dashboard counts the urgent requests that are not resolved and says it in the to-do list', tile2.count === '1' && /1 demande urgente n’est pas résolue\./.test(tile2.todo), JSON.stringify([tile, tile2]));
await s.page.evaluate(() => [...document.querySelectorAll('#dashboard-tiles a')].find((a) => /Demandes urgentes non résolues/.test(a.getAttribute('aria-label'))).click());
await wait(400);
const viaDashboard = await s.page.evaluate(() => ({ priority: document.querySelector('#staff-filter-priority').value, status: document.querySelector('#staff-filter-status').value, shown: [...document.querySelectorAll('#staff-messages .message-card h4')].map((h) => h.textContent) }));
check('opening that dashboard number lists exactly those requests (priority urgent, state "Non résolues")', viaDashboard.priority === 'urgent' && viaDashboard.status === 'open' && viaDashboard.shown.length === 1 && /Lampadaire/.test(viaDashboard.shown[0]), JSON.stringify(viaDashboard));
await s.page.select('#staff-filter-priority', '');
await s.page.select('#staff-filter-status', '');
await s.page.click('#lang-toggle');
await s.page.waitForFunction(() => /^⚠ Urgent$/.test(document.querySelector('#staff-messages .message-priority')?.textContent || ''), { timeout: 8000 }).catch(() => {});
const staffEnglish = await s.page.evaluate(() => ({ badge: document.querySelector('#staff-messages .message-priority')?.textContent, options: [...document.querySelector('[data-priority-for]').options].map((o) => o.textContent), filter: document.querySelector('label:has(#staff-filter-priority)')?.firstChild?.textContent.trim(), sort: document.querySelector('#staff-sort option[value=oldest]')?.textContent }));
check('in English the badge, the selector, the filter and the sort read in English', staffEnglish.badge === '⚠ Urgent' && JSON.stringify(staffEnglish.options) === JSON.stringify(['Urgent', 'High priority', 'Normal']) && staffEnglish.filter === 'Priority' && staffEnglish.sort === 'Oldest first', JSON.stringify(staffEnglish));
await s.context.close();
s = await open(zoe);
await s.page.waitForSelector('#citizen-messages .message-card');
const residentSees = await s.page.evaluate(() => document.querySelector('#citizen-area').textContent);
check('the resident never sees the priority their request was given (it is internal)', !/Urgente|Prioritaire|Priorité/.test(residentSees), residentSees.match(/.{20}(Urgente|Prioritaire|Priorité).{20}/)?.[0]);
await s.context.close();

await browser.close();
server.kill();
await wait(400);
rmSync(dataDir, { recursive: true, force: true, maxRetries: 5, retryDelay: 200 });
console.log(failures ? `\n${failures} FAILED` : '\nall civic UI checks passed');
process.exit(failures ? 1 : 0);
