// Builds coordination/reports/A-final-feature-audit.md (per-code table for the 96-code release) from the hand-kept evidence map below.
import { writeFileSync } from 'node:fs';
const L = 'local'; // disposable-data suites run on the exact released source (b1404e7 = application of 1db994a)
const P = 'live'; // tools/qa-a/prod-signed-in.mjs (52 checks) and host-smoke on the deployed host
const rows = [
  ['D01', 'PASS', 'register with or without e-mail, password rules; ' + L + ': smoke/portal/auth-browser; ' + P + ': register (signed token) + login', ''],
  ['D02', 'PASS-virtual', 'passkeys (maintained @simplewebauthn/server 14.0.3); ' + L + ': passkeys 77 protocol + real-Chrome virtual authenticator', 'real devices / security keys UNVERIFIED; WebAuthn on the https origin UNVERIFIED'],
  ['D03', 'PASS', 'sessions 7 days, device recognition; ' + L + ' + ' + P + ': all roles sign in', ''],
  ['D04', 'PASS', 'message form to the services; ' + L + ' + ' + P + ' (TEST request created, answered)', ''],
  ['D05', 'PASS', 'services list, search, featured, availability, orientation helper (B); ' + L + ': portal/smoke; ' + P + ': /api/services fields', ''],
  ['D06', 'PASS', 'news with audience and urgent banner; ' + L + ': smoke/auth-browser; ' + P + ': /api/announcements', ''],
  ['D07', 'PARTIAL', 'home: emergency strip, guide "Je viens d\'arriver", nav and skip links; ' + L + ': a11y/portal-browser', 'comprehension by a first-time visitor is a human judgement: UNVERIFIED'],
  ['D08', 'PASS', 'roles citizen/agent/admin with distinct spaces; ' + L + ': smoke 4 roles; ' + P + ': 3 roles + limited agent', ''],
  ['D09', 'PASS', 'role gates, own-data isolation, F70 perimeter; ' + L + ': smoke + scoping 16; ' + P + ': 403/401/404 cases', ''],
  ['D10', 'B', 'orientation helper (B module, integrated)', 'see B-final-feature-audit'],
  ['D11', 'PASS', 'request history with state in words, dates, references, receipts; ' + L + ' + ' + P + ' (Alice history)', ''],
  ['D12', 'PASS', 'dismissible first-login guide per user; ' + L + ': portal-browser', ''],
  ['D13', 'PASS', 'plain wording + glossary FR/EN; ' + L + ': a11y/portal-audit', 'reading level not measured'],
  ['D14', 'PARTIAL', 'FR/EN interface and service content with fallback to French; ' + L + ': portal/civic/auth-browser', 'only two languages; no browser-language auto detection claimed'],
  ['D15', 'PASS', 'breadcrumbs, focus targets and jump links in the personal space; ' + L + ': a11y keystroke counts', ''],
  ['D16', 'PASS', 'confirmation + reference + receipt page + public verification; ' + L + ': receipts-replies 30; ' + P + ': receipt validated publicly', ''],
  ['D17', 'PASS', 'staff list with filters (state, type, district, theme, priority), dashboard; ' + L + ' + ' + P, ''],
  ['D18', 'PASS', 'urgent alert banner on every page, audience, official sender (F73); ' + L + ': auth-browser/smoke; ' + P + ': announcements', ''],
  ['D19', 'PASS', 'OFFICIAL wording: staff get their own workspace, distinct from the citizen space, showing the information sent by the Nova Terra API. Implementation: role-gated staff area (#staff-area, jump nav, dashboard) + GET /api/requests (agent/admin only) reading the official feed with the server-only X-Webcup-Api-Key, 15 s cache, errors 503 (key missing) / 502 (refused, unavailable, invalid); panels "Flux officiel Terra Nova" and "Demandes du concours". ' + L + ': smoke (401/403/200, error cases) + a11y/portal-browser staff pages; ' + P + ': anonymous 401, citizen 403, agent 200, admin 200, body = api_version, session, 100 requests, no key in the body', 'the key is never shown to any client (checked: absent from the body); a key-less deployment shows the 503 message in words'],
  ['D20', 'PARTIAL', 'axe 0 violations on portal states, keyboard, zoom, contrast, reduced motion; ' + L + ': a11y-browser 100', 'real screen readers UNVERIFIED'],
  ['F21', 'PARTIAL', 'labels, landmarks, live statuses, axe clean; ' + L + ': a11y-browser', 'NVDA/JAWS/VoiceOver not run: UNVERIFIED'],
  ['F22', 'PASS', 'staff receive and triage requests; ' + L + ' + ' + P, ''],
  ['F23', 'PASS', 'high-contrast mode + system preference; ' + L + ': a11y-browser/axe', ''],
  ['F24', 'PASS', 'text size control to 200 %; ' + L + ': a11y-browser', ''],
  ['F25', 'PASS', 'report a problem with place, theme and service; ' + L + ' + ' + P, ''],
  ['F26', 'PASS', 'history with dates and states; ' + L + ' + ' + P, ''],
  ['F27', 'PARTIAL', 'service titles, descriptions and details in English with French fallback (>= 3 genuinely translated services live: prod-signed-in); ' + L + ': portal/civic', 'official wording says several languages: only FR and EN exist'],
  ['F28', 'PASS', 'featured first and highlighted; admin toggle; ' + L + ': smoke; ' + P + ': field present', ''],
  ['F29', 'PASS', 'urgent alert for an audience; ' + L + ': smoke/auth-browser', ''],
  ['F30', 'PASS', 'opt-in browser notification for new urgent items; ' + L + ': smoke (permission API stubbed)', 'real OS notification UNVERIFIED'],
  ['F31', 'PASS', 'heat-wave style alert with instructions in a role=alert banner; ' + L + ' + ' + P + ' (seeded alerts visible)', ''],
  ['F32', 'PASS', 'search as you type; ' + L + ': portal-browser', ''],
  ['F33', 'PASS', 'self-deletion with password, cascade; ' + L + ': smoke + participation-integration; ' + P + ': TEST account deleted, no residue', ''],
  ['F34', 'PASS', 'staff administer citizen accounts (list, deactivate, reset, delete) + counter accounts; ' + L + ': smoke/passkeys/auth-browser', ''],
  ['F35', 'PASS', 'contextual dismissible tips; ' + L + ': portal-browser', ''],
  ['F36', 'PASS(portal) / B(world)', 'transports API, stops, next departures, disruptions; ' + L + ' + ' + P, 'world tram: B'],
  ['F37', 'PASS', 'per-pair/account/address limits, tries left, lock, notice of failed attempts, staff list; ' + L + ': smoke; ' + P + ': tries-left answers', ''],
  ['F38', 'PASS', 'service status + reason + return date before starting; ' + L + ': smoke', 'toggle not exercised on live to keep jury data intact'],
  ['F39', 'PASS', 'staff slots, resident booking with reason, cancel; ' + L + '; ' + P + ': booked + cancelled', ''],
  ['F40', 'PASS', '24 h banner, notification opt-in, .ics with VALARM; ' + L + '; ' + P + ': .ics VALARM', 'the 24 h banner needs a slot inside 24 h: local only'],
  ['F41', 'PASS', 'keyboard only: tab order, focus, skip links, 16/18 keystroke budgets; ' + L + ': a11y-browser', ''],
  ['F42', 'PASS', 'labels, hints, aria-invalid, focus to first error, live statuses; ' + L + ': a11y-browser', ''],
  ['F43', 'PASS', 'never colour alone; contrast modes; ' + L + ': a11y/axe', ''],
  ['F44', 'PASS', '200 % zoom and 320 px reflow; ' + L + ': a11y-browser', ''],
  ['F45', 'PASS', 'places/services with address, hours, stop, next tram; ' + L + '; ' + P, ''],
  ['F46', 'PASS', 'emergency strip, hospital/emergency places with phone and hours; ' + L + '; ' + P + ': places', ''],
  ['F47', 'PASS', 'append-only hash-chained journal; ' + L + ': smoke; ' + P + ': chain verifies', ''],
  ['F48', 'PASS', 'journal filters, plain lines, CSV; ' + L + '; ' + P, ''],
  ['F49', 'PASS', 'notices on every status change and reply; ' + L + '; ' + P + ': notices appear', ''],
  ['F50', 'PASS', 'staff dashboard with linked numbers; ' + L + '; ' + P, ''],
  ['F51', 'PASS', '"Vos données" page, export JSON, data concern; ' + L + '; ' + P + ': export has no secrets', ''],
  ['F52', 'PASS', 'public anonymised reports, one support each; ' + L + '; ' + P + ': publish/support/withdraw', ''],
  ['F53', 'PASS-virtual', 'TOTP + recovery codes; ' + L + ': second-step 40 + RFC vectors; ' + P + ': set up, sign in, replay refused, recovery, off', 'real authenticator app UNVERIFIED'],
  ['F54', 'PASS', 'new-device notice and device list; ' + L + '; ' + P + ': devices list', ''],
  ['F55', 'PASS', 'readable personal summary + export; ' + L + '; ' + P, ''],
  ['F56', 'PASS', 'CSV and printable recap; ' + L + ': smoke', ''],
  ['F57', 'PARTIAL', 'EVALUATION as measured proxies (tools/qa-a/perf-portal.mjs, report coordination/reports/perf-portal-final-4a5.json): visitor home cold 10 requests / 75.8 KB (was 17), warm 0.3 KB, hidden tab 0 requests in 66 s; improvements: gzip/brotli, ETag, lazy modules, essentials mode', 'proxies only: no carbon/energy figure or external audit (UNVERIFIED claim of environmental impact)'],
  ['F58', 'PASS', 'sober loading choices on the main journeys (compression, revalidation, lazy modules, essentials mode, hidden-tab polling pause, saved copies); ' + L + ': perf-portal + essentials-browser', 'long-term effect not measurable'],
  ['F59', 'PASS-local', 'measured under the slow-3g profile: visitor home load ~2.0 s / 75.8 KB, warm 0.15 s; essentials mode; saved copy after 6 s; ' + L + ': perf-portal + essentials-browser', 'real slow network UNVERIFIED'],
  ['F60', 'PARTIAL', 'portal has no heavy images; world assets are B (GLB local); ' + L, 'media weight of /monde/ is B'],
  ['F61', 'UNVERIFIED', 'no low-power device run', 'needs real low-end hardware'],
  ['F62', 'PASS', 'essentials mode toggle (+ data-saver auto); ' + L + ': essentials-browser 22', ''],
  ['F63', 'PASS', 'admin availability toggle disables a service for residents at once; ' + L + ': smoke', 'not toggled live (jury data)'],
  ['F64', 'PASS', 'availability, reason, alternative before starting a procedure; ' + L, ''],
  ['F65', 'B', 'participation votes (B module, integrated)', 'see B-final-feature-audit; ' + L + ': participation-integration 29'],
  ['F66', 'B', 'consultations (B module)', ''],
  ['F67', 'B', 'projects (B module)', ''],
  ['F68', 'B', 'ideas (B module)', ''],
  ['F69', 'PARTIAL', 'strict CSP, escaping, validation, body/Origin limits, rate limits, form guard, maintained WebAuthn; ' + L + ': smoke/form-protection/passkeys (hostile CBOR)', 'no independent penetration test: UNVERIFIED'],
  ['F70', 'PASS', 'role gates + per-agent perimeter (list, count, 404, journal); ' + L + ': scoping 16; ' + P + ': limited agent'],
  ['F71', 'PARTIAL', 'e-mail optional, access code, counter-opened accounts, password change, FR/EN; ' + L + '; ' + P, 'only 2 languages for ~500 new residents'],
  ['F72', 'PASS', '"Je viens d\'arriver" guide, 4 situations, real links, no account; ' + L + ': served live (/ has #debuter)', 'dedicated browser assertion added (essentials-browser F72 section)'],
  ['F73', 'PASS', 'Haut Conseil sender, banner for all, first in news; ' + L + ': ops-api/auth-browser; ' + P + ': field handled', ''],
  ['F74', 'PASS', 'partner places with address/hours; ' + L + '; ' + P + ': partner place present', ''],
  ['F75', 'PASS', 'lexical grouping for staff; ' + L + ': triage-api/civic-browser; ' + P + ': 2 similar TEST requests grouped', 'different wording is not matched (stated in the UI)'],
  ['F76', 'B', 'service feedback (B module)', ''],
  ['F77', 'UNVERIFIED', 'bounded behaviours (polling pause, saved copy, limits); no load test run', 'no stress allowed on the host'],
  ['F78', 'UNVERIFIED', 'same; stable under ordinary use', 'concurrent-user capacity not measured'],
  ['F79', 'PASS', 'theme model, sort/filter for resident, reports, staff; ' + L + '; ' + P, ''],
  ['F80', 'PASS', 'priority levels, badge, order, filter; ' + L + '; ' + P, ''],
  ['F81', 'PASS', 'hidden field, signed single-use tokens, quotas; ' + L + ': form-protection 35; ' + P + ': robot refused', ''],
  ['F82', 'PASS', 'idempotent replay + duplicate fingerprint; ' + L + '; ' + P + ': duplicate -> same id', ''],
  ['F83', 'PASS', 'reference, receipt page, public check; ' + L + '; ' + P, ''],
  ['F84', 'PASS', 'agent replies with notice + thread; ' + L + '; ' + P, ''],
  ['F85', 'PASS', 'anomaly list + consistency check; ' + L + ': ops-api (tamper detected); ' + P + ': answers', 'tamper detection local only'],
  ['F86', 'PASS', 'emergency flag, 112 warning, top of staff list, dashboard; ' + L + '; ' + P + ': fictional scenario flagged', ''],
  ['F87', 'PASS', 'backup verification report; ' + L + '; ' + P + ': ok, copy deleted', 'restore test not done'],
  ['F88', 'PASS', 'chosen-column CSV/JSON export, scope aware, journalled; ' + L + '; ' + P, ''],
  ['F89', 'B', 'plain-language explanations (B)', ''],
  ['F90', 'B', 'on-demand explanation (B)', ''],
  ['F91', 'B', 'orientation assistant (B)', ''],
  ['F92', 'B', 'right service from a description (B)', ''],
  ['F93', 'PARTIAL', 'service worker keeps public essentials; stale banner with date; ' + L + ': essentials-browser (server stopped)', 'real https/host outage UNVERIFIED; writes need a connection (stated)'],
  ['F94', 'PASS', 'emergency numbers, alerts, services, places with phones readable offline; ' + L, 'private data deliberately not cached'],
  ['F95', 'PASS', 'first guest load 17 -> 10 requests; modules open on request; ' + L + ': essentials-browser', ''],
  ['F96', 'PARTIAL', 'essentials mode on phone widths; ' + L + ': essentials-browser 390 px', 'real device and real throttled network UNVERIFIED'],
];
const head = '# A final feature audit (96-code release, application source b1404e7 = deployed 1db994a)\n\nLegend: PASS = implemented and exercised (local = disposable-data suites on this source; live = tools/qa-a/prod-signed-in.mjs 52/52 + host-smoke on the deployed host). PASS-virtual = automated virtual proof only. PARTIAL / UNVERIFIED / B (owned by B, see B-final-feature-audit.md).\nNo defect was reproduced in this audit; the only failures were three wrong expectations inside the new live script (fixed). Remaining human/device gaps are listed per row.\n\n| Code | Status | Evidence | Remaining / UNVERIFIED |\n|---|---|---|---|\n';
const body = rows.map((r) => `| ${r[0]} | ${r[1]} | ${r[2]} | ${r[3] || ''} |`).join('\n');
const counts = rows.reduce((m, r) => { const k = r[1].split(/[ (]/)[0]; m[k] = (m[k] || 0) + 1; return m; }, {});
writeFileSync(process.argv[2], `${head}${body}\n\nCounts: ${JSON.stringify(counts)} of ${rows.length}.\nSuites (paths under tools/qa-a): smoke-a (tools/), portal, portal-audit, portal-browser, a11y-browser, forms-browser, civic-browser, auth-browser, essentials-browser, ops-api, scoping, passkeys, second-step, receipts-replies, form-protection, triage-api, migration-old-db, participation-integration, prod-signed-in, host-smoke.\n`);
console.log(JSON.stringify(counts), rows.length);
