import puppeteer from 'puppeteer-core';
const [base] = process.argv.slice(2);
let bad = 0; const check = (n, ok, info='') => { if (!ok) bad++; console.log(ok?'PASS':'FAIL', n, info); };
const b = await puppeteer.launch({ executablePath: 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe', headless: 'new', args: ['--use-angle=swiftshader','--enable-unsafe-swiftshader'] });
const p = await b.newPage(); await p.setViewport({ width: 1280, height: 800 });
p.on('pageerror', e => console.log('pageerror', e.message));
await p.goto(base + '/', { waitUntil: 'networkidle0' });
await p.evaluate(async () => {
  const post=(u,m,b)=>fetch(u,{method:m,headers:{'Content-Type':'application/json'},body:JSON.stringify(b)});
  await post('/api/auth/register','POST',{name:'Matrix3',email:`mx3${Date.now()}@example.org`,password:'motdepasse-solide-123'});
  await post('/api/me/avatar','PUT',{skin:'#e0ac69',outfit:'#3a6ea5',accent:'#ff4fa3'});
  const {user}=await(await fetch('/api/me')).json();
  localStorage.setItem(`world-seen-alerts:${user.id}`,JSON.stringify(Array.from({length:200},(_,i)=>i)));
});
await p.goto(`${base}/monde/?debug`, { waitUntil: 'networkidle0' });
await p.waitForFunction(() => window.__tn);
await new Promise(r=>setTimeout(r,2500));
// first-login avatar editor auto-opens: cancel it
await p.evaluate(() => { const b=[...document.querySelectorAll('dialog.avatar-editor button')].find(x=>/Annuler|Cancel/.test(x.textContent)); b?.click(); });
await new Promise(r=>setTimeout(r,400));
await p.keyboard.press('KeyT'); await new Promise(r=>setTimeout(r,1200));
check('open: phone host visible with text', await p.evaluate(() => { const h=document.querySelector('.phone-host'); return h && getComputedStyle(h).opacity==='1' && h.textContent.trim().length>0; }));
await p.keyboard.press('KeyT'); await new Promise(r=>setTimeout(r,1200));
check('close: phone host hidden/gone', await p.evaluate(() => { const h=document.querySelector('.phone-host'); return !h || getComputedStyle(h).opacity==='0'; }));
await p.evaluate(() => { const b=[...document.querySelectorAll('button')].find(x=>/Mon colon/.test(x.textContent)); b?.click(); });
await new Promise(r=>setTimeout(r,500));
check('avatar editor opens', await p.evaluate(() => !!document.querySelector('dialog.avatar-editor[open]')));
await p.keyboard.press('KeyT'); await new Promise(r=>setTimeout(r,700));
check('phone does not open while avatar editor is open (no dual overlay)', await p.evaluate(() => !document.querySelector('.phone-host') || getComputedStyle(document.querySelector('.phone-host')).opacity==='0'));
await p.evaluate(() => { const b=[...document.querySelectorAll('dialog.avatar-editor button')].find(x=>/Annuler|Cancel/.test(x.textContent)); b?.click(); });
await new Promise(r=>setTimeout(r,500));
const z0 = await p.evaluate(() => window.__tn.ecctrl?.body.translation().z);
await p.keyboard.press('KeyT'); await new Promise(r=>setTimeout(r,1200));
await p.keyboard.press('KeyT'); await new Promise(r=>setTimeout(r,1200));
await p.keyboard.down('KeyW'); await new Promise(r=>setTimeout(r,600)); await p.keyboard.up('KeyW');
const z1 = await p.evaluate(() => window.__tn.ecctrl?.body.translation().z);
check('movement restored after open+close cycle', Math.abs(z1-z0) > 0.03, `${z0} -> ${z1}`);
await b.close();
console.log(bad ? `FAILURES (${bad})` : 'ALL PASS');
process.exit(bad?1:0);
