// Disposable database shaped like A's committed schema, with A's seed texts for services and places (copied from A's store.mjs seeds), for the orientation checks.
import { DatabaseSync } from 'node:sqlite';

export function seededDb() {
  const db = new DatabaseSync(':memory:');
  db.exec(`
    CREATE TABLE services (id INTEGER PRIMARY KEY, title TEXT NOT NULL, description TEXT NOT NULL, details TEXT NOT NULL, featured INTEGER NOT NULL DEFAULT 0,
      title_en TEXT, description_en TEXT, details_en TEXT, availability TEXT NOT NULL DEFAULT 'available', unavailable_reason TEXT, unavailable_reason_en TEXT, available_again TEXT, alternative TEXT, alternative_en TEXT);
    CREATE TABLE places (id INTEGER PRIMARY KEY, code TEXT NOT NULL UNIQUE, kind TEXT NOT NULL, name TEXT NOT NULL, name_en TEXT, district TEXT NOT NULL, stop TEXT NOT NULL, address TEXT NOT NULL, address_en TEXT,
      hours TEXT, hours_en TEXT, open_24h INTEGER NOT NULL DEFAULT 0, phone TEXT, service_id INTEGER);
  `);
  const svc = db.prepare('INSERT INTO services (title, description, details, featured, title_en, description_en, details_en) VALUES (?, ?, ?, ?, ?, ?, ?)');
  svc.run('Relations citoyennes', 'Une question ou une difficulté ?', 'Depuis votre espace personnel, envoyez un message aux services municipaux et suivez son traitement.', 0, 'Citizen relations', 'A question or a difficulty?', 'From your personal space, send a message to the city services and follow how it is handled.');
  svc.run('Espace personnel', 'Vos démarches au même endroit.', 'Créez un compte pour accéder à vos informations et retrouver vos échanges avec la ville.', 0, 'Personal space', 'All your requests in one place.', 'Create an account to access your information and find your conversations with the city.');
  svc.run('Suivi des demandes', 'Gardez une trace de vos échanges.', 'Consultez le statut de chaque message : reçu, en cours de traitement ou résolu.', 0, 'Request tracking', 'Keep track of your conversations.', 'Check the status of each message: received, in progress or resolved.');
  svc.run('Centre de santé', 'Consultations, vaccinations et soins de proximité.', 'Le centre de santé municipal reçoit les habitants pour la médecine générale, les vaccinations et les soins infirmiers. Pour prendre rendez-vous, envoyez un message depuis votre espace personnel.', 1, 'Health centre', 'Consultations, vaccinations and local care.', 'The city health centre welcomes residents for general medicine, vaccinations and nursing care. To book an appointment, send a message from your personal space.');
  svc.run('Signaler un problème', 'Lampadaire cassé, voirie, propreté…', 'Depuis votre espace personnel, choisissez « Signaler un problème », décrivez ce qui s’est passé et indiquez le lieu. Vous suivez ensuite son traitement.', 1, 'Report a problem', 'Broken street light, roads, cleanliness…', 'From your personal space, choose “Report a problem”, describe what happened and give the location. You can then follow how it is handled.');
  svc.run('Prévention et santé publique', 'Chaleur, montée des eaux, épidémies : les bons gestes.', 'Le service de prévention informe sur les risques sanitaires et accompagne les personnes vulnérables. Les alertes en cours s’affichent en haut de chaque page ; activez les notifications pour être prévenu.', 0, 'Prevention and public health', 'Heat, rising water, epidemics: what to do.', 'The prevention service informs residents about health risks and supports vulnerable people. Active alerts appear at the top of every page; turn on notifications to be warned.');
  const place = db.prepare('INSERT INTO places (code, kind, name, name_en, district, stop, address, address_en, hours, hours_en, open_24h, phone, service_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)');
  place.run('mairie', 'service', 'Mairie', 'Town hall', 'Centre-ville', 'Mairie', 'Sur la place centrale, le grand bâtiment avec l’antenne. Accueil et rendez-vous à l’entrée sous l’auvent.', 'On the central square, the large building with the antenna. Reception and appointments at the entrance under the canopy.', 'Du lundi au vendredi, de 8 h à 17 h', 'Monday to Friday, 8 am to 5 pm', 0, null, null);
  place.run('hopital-terra-nova', 'hospital', 'Hôpital de Terra Nova', 'Terra Nova hospital', 'Quartier est', 'Santé', 'Quartier est, à côté de l’arrêt Santé. Grand bâtiment clair avec une croix verte.', 'East district, next to the Santé stop. Large pale building with a green cross.', 'Ouvert 24 h sur 24', 'Open 24 hours', 1, '112', null);
  place.run('urgences-hopital', 'emergency', 'Urgences de l’hôpital', 'Hospital emergency room', 'Quartier est', 'Santé', 'Entrée des urgences sur le côté nord de l’hôpital, bien indiquée. Elle est ouverte jour et nuit.', 'Emergency entrance on the north side of the hospital, clearly signposted. Open day and night.', 'Ouvert 24 h sur 24', 'Open 24 hours', 1, '112', null);
  place.run('centre-sante', 'service', 'Centre de santé', 'Health centre', 'Quartier est', 'Santé', 'Quartier est, en face de l’arrêt Santé. Soins de proximité, vaccinations, consultations.', 'East district, opposite the Santé stop. Local care, vaccinations, consultations.', 'Du lundi au samedi, de 8 h à 18 h', 'Monday to Saturday, 8 am to 6 pm', 0, null, 4);
  place.run('secours-quartier-sud', 'emergency', 'Poste de secours du quartier sud', 'South district rescue post', 'Quartier sud', 'Quartier sud', 'Quartier sud, près des berges, à côté de l’arrêt Quartier sud. Secours en cas d’inondation.', 'South district, near the riverbank, next to the Quartier sud stop. Rescue in case of flooding.', 'Ouvert 24 h sur 24', 'Open 24 hours', 1, '112', null);
  place.run('point-accueil-habitat', 'service', 'Point d’accueil d’Habitat', 'Habitat help desk', 'Quartier nord', 'Habitat', 'Quartier nord, au pied des logements, près de l’arrêt Habitat. Aide pour vos démarches.', 'North district, at the foot of the housing blocks, near the Habitat stop. Help with your procedures.', 'Du mardi au jeudi, de 9 h à 16 h', 'Tuesday to Thursday, 9 am to 4 pm', 0, null, null);
  place.run('marche-couvert', 'service', 'Marché couvert', 'Covered market', 'Quartier ouest', 'Marché', 'Quartier ouest, à côté de l’arrêt Marché. Étals sous auvent ; information pour les commerçants.', 'West district, next to the Marché stop. Stalls under awnings; information for traders.', 'Du mardi au samedi, de 7 h à 13 h', 'Tuesday to Saturday, 7 am to 1 pm', 0, null, null);
  return db;
}
